import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CanvasDraw from "react-canvas-draw";
import { useRef, useState } from 'react';

const canvasProps = {
  onChange: null,
  loadTimeOffset: 5,
  lazyRadius: 0,
  brushRadius: .5,
  brushColor: "#444",
  catenaryColor: "#0a0302",
  gridColor: "rgba(150,150,150,0.17)",
  hideGrid: false,
  disabled: false,
  imgSrc: "",
  saveData: null,
  immediateLoading: false,
  hideInterface: false,
  gridSizeX: 25,
  gridSizeY: 25,
  gridLineWidth: 0.5,
  hideGridX: false,
  hideGridY: false,
  enablePanAndZoom: true,
  mouseZoomFactor: 0.01,
  zoomExtents: { min: 0.33, max: 3 },
};

export default function Home() {

  const [drawing, setDrawing] = useState(false)
  const canvasRef = useRef()

  var ctx = canvasRef.current?.getContext("2d");

  const drawOnCanvas = (evt) => {
    if(!drawing) return
    var rect = canvasRef.current.getBoundingClientRect();
    let x = evt.clientX - rect.left, y = evt.clientY - rect.top
    ctx.lineWidth = 10;
    ctx.lineCap = 'round'
    ctx.lineJoin = 'round';
    ctx.lineTo(x, y)
    ctx.stroke()
    ctx.beginPath()
    ctx.moveTo(x, y)
  }

  const resetEvents=()=>{
    setDrawing(false)
    ctx.beginPath()
  }


  return (
    <div className={styles.container}>
      
      <Head>
        <title>Skribbl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src='https://cdnjs.cloudflare.com/ajax/libs/css-doodle/0.2.2/css-doodle.min.js' ></script>

        
      </Head>

      <main className={styles.main}>
  

        <canvas
          ref={canvasRef}
          height='600px'
          width='800px'
          style={{ border: '1px solid black' }}
          onMouseMove={drawOnCanvas}
          onMouseOut={resetEvents}
          onMouseDown={() => setDrawing(true)}
          onMouseUp={resetEvents}
        >
          Canvas is not supported in your Browser
        </canvas>
      </main>

      <footer className={styles.footer}>
        Created by - kaka ke papa
      </footer>
    </div>
  )
}




/* <CanvasDraw
          {...canvasProps}
          // canvasWidth={window.innerWidth / 1.5}
          // canvasHeight={window.innerWidth / 1.5}
          style={{
            cursor:'none',
            boxShadow:
              "0 13px 27px -5px rgba(50, 50, 93, 0.25),    0 8px 16px -8px rgba(0, 0, 0, 0.3)"
          }}
        /> */